### ISSUE TITLE
Allow SLV to work in communities

### ISSUE THREAD

**Issue by tomansley** [tomansley/SimpliListViews#118]
**Describe the bug**
Allow SLV to work in communities

Submitted by Andrew.Mishler@wave6.com

**Comment by tomansley** [comment]
Resolved in v2.137

**Comment by huynhwaker** [comment]
Could use some help on this. This is how it's appearing in my community, but it should have records.
![Screenshot 2024-04-05 at 2 49 06 PM](https://github.com/tomansley/SimpliListViews/assets/44445020/b011ec12-1d73-480c-91ea-dc59e9797013)

**Comment by tomansley** [comment]
Make very sure all permissions for all simpli list view records and displayed records are correct.

Communities has weird permission requirements in my experience. But, others do use SLV with communities and it seems to work for them.
________________________________

**Comment by huynhwaker** [comment]
Really appreciate the response. Communities does have weird permissions. I'll look into it further, but at this time the profile I tried to open up permissions for, there was no checkbox to toggle for View All/Modify All. This may be because it's a Customer Community License. If I get stuck again I'll let ya know.

**Comment by tomansley** [comment]
Oh man! Customer community license is like a strait jacket. Definitely let me know how it goes. I'll poke around and see what I find as well.
________________________________
