### ISSUE TITLE
List view not available for CPQ PriceBookEntry object

### ISSUE THREAD

**Issue by YRSusmitha** [tomansley/SimpliListViews#12]
I am not able to create '2 List view' for CPQ objects PriceBook and PriceBookEntry 

![listview](https://user-images.githubusercontent.com/58733639/110511016-14939280-8104-11eb-9acf-bd069cf66e07.JPG)

**Comment by tomansley** [comment]
Hello - 

Thanks for posting this issue. I will look into it but have a feeling that the price book might be a special object creating problems for the app.

Will keep you posted through this thread.

Cheers
Tom

**Comment by tomansley** [comment]
Hello - I am looking into this issue and do not see any standard list views for price book. I do see standard list views for price book entry.

Do you have standard list views for price book? If so how do you get to them?

Thanks
Tom

**Comment by tomansley** [comment]
Hello - I looked into this issue further. I have not worked with CPQ a lot so might have some assumptions incorrect, but I have been able to get the standard pricebook2 and pricebookentry objects working in Simpli List View successfully. The pricebookentry object allows list views but it doesn't look like the pricebook2 object does. I had to use the advanced custom list view functionality in order to create a list view for pricebook2. I then also went further and was able to create a lightning page with 2 list views where the left is the pricebook2 object and the right is the pricebookentry object. When selecting a pricebook2 row the pricebookentry list view updates as expected.

I have attached some screenshots here of the list views in action as well as some configuration pages. I will add information on how to create the pricebook2 list view soon.

Please let me know if this resolves your issue.

Thanks
Tom
![Screen Shot 2021-03-14 at 2 46 07 PM](https://user-images.githubusercontent.com/375321/111082010-1a0e2580-84d4-11eb-9fa3-07cb15be9d66.png)

![Screen Shot 2021-03-14 at 2 46 26 PM](https://user-images.githubusercontent.com/375321/111082014-1d091600-84d4-11eb-8e32-abd9af6a438d.png)

![Screen Shot 2021-03-14 at 2 44 11 PM](https://user-images.githubusercontent.com/375321/111081972-e0d5b580-84d3-11eb-8fd1-54607b055430.png)

**Comment by YRSusmitha** [comment]
Hello Tom,
Greetings!!
Thank you for looking into the issue and updating me. I ll check and let
you know my observations.

Kind regards,
Susmitha.
