### ISSUE TITLE
Managed Package Fields Displaying API Names

### ISSUE THREAD

**Issue by dbsfhub** [tomansley/SimpliListViews#132]
**Describe the bug**
It's possible I am missing a setting but only for fields in Managed Packed I am seeing the API Field Name and never the Field Name as the column headers. I've tried a few different objects that meet this criteria with the same outcome while custom and standard display the name value as expected. In the screenshot you can see the standard field displays the field name and the fields from the package are API.

**Simpli List View Version**
2.146

**To Reproduce**
1. Choose an object from a Managed Package
2. Choose a List View
3. List View displays using API Field Names as column headers

**Expected behavior**
The field name like with other List Views.

**Screenshots**
![image](https://user-images.githubusercontent.com/108283681/205329429-cd4ccb33-841c-41f8-80ba-2b6ea3ddbe7d.png)

**Desktop (please complete the following information):**
 - All Chromium

**Comment by tomansley** [comment]
This should be able to be resolved by going to the admin tab and selecting NO for the “Add Object Name On Lookup Labels”

 

From: dbsfhub ***@***.***> 
Sent: Friday, December 2, 2022 9:41 AM
To: tomansley/SimpliListViews ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tomansley/SimpliListViews] Managed Package Fields Displaying API Names (Issue #132)

 

Describe the bug
It's possible I am missing a setting but only for fields in Managed Packed I am seeing the API Field Name and never the Field Name as the column headers. I've tried a few different objects that meet this criteria with the same outcome while custom and standard display the name value as expected. In the screenshot you can see the standard field displays the field name and the fields from the package are API.

Simpli List View Version
2.146

To Reproduce
Steps to reproduce the behavior:

1.	Choose an object from a Managed Package
2.	Choose a List View
3.	List View displays using API Field Names as column headers

Expected behavior
The field name like with other List Views.

Screenshots
 <https://user-images.githubusercontent.com/108283681/205329429-cd4ccb33-841c-41f8-80ba-2b6ea3ddbe7d.png> 

Desktop (please complete the following information):

*	All Chromium

**Comment by dbsfhub** [comment]
I knew I was missing something - that did it! Thank you! I just realized that it removed all my settings on that page when I installed the updated version you provided. I had added the object exclusions back but missed that setting.
