### ISSUE TITLE
Simple list view doesnt' show any data

### ISSUE THREAD

**Issue by martingaleh** [tomansley/SimpliListViews#138]
**Describe the bug**
After creating a custom list view, no data is visible

**Simpli List View Version**
What version of SLV is currently being used?
It's not obvious where to look among all the tabs we're presented.  Maybe 2.147 from the installed package

**To Reproduce**
Create a listview in the method approximated by youtube to acheive the configuration details provided in the pictures below

**Expected behavior**
A list view should appear, but instead, the soql construction is incorrect 

**Screenshots**
Here is the workbench
![image](https://user-images.githubusercontent.com/283459/221448785-d0e951f6-2720-4e51-8b33-0c6e951aad0b.png)

Here is the. setup with the same exact soql
![image](https://user-images.githubusercontent.com/283459/221448853-5af508c5-1fa1-4158-9e90-f899eabe272e.png)
![image](https://user-images.githubusercontent.com/283459/221448886-ea378bf1-a285-4d3b-b56e-d80ad0b1d537.png)
```[{"fieldNameOrPath":"Id","type":"Id","label":"Account Id"},{"fieldNameOrPath":"Sales_Orders__r.Id","type":"Id","label":"Sales Orders Id"},{"fieldNameOrPath":"Sales_Orders__r.Name","type":"String","label":"Sales Order Name Id"}]```
Here is the issue in the event log:
![image](https://user-images.githubusercontent.com/283459/221448990-4a4d756d-6b3d-43f0-b945-434655232105.png)

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**

**Comment by tomansley** [comment]
Martin,

Try using ALL CAPS for the query keywords. So it would be -

SELECT id FROM obj WHERE.....

I probably need to fix that!

Cheers
Tom
________________________________
From: martingaleh ***@***.***>
Sent: Sunday, February 26, 2023 6:58:54 PM
To: tomansley/SimpliListViews ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tomansley/SimpliListViews] Simple list view doesnt' show any data (Issue #138)


Describe the bug
After creating a custom list view, no data is visible

Simpli List View Version
What version of SLV is currently being used?
It's not obvious where to look among all the tabs we're presented. Maybe 2.147 from the installed package

To Reproduce
Steps to reproduce the behavior:
Create a listview in the method approximated by youtube to acheive the configuration details provided in the pictures below

Expected behavior
A clear and concise description of what you expected to happen.
A list view should appear, but instead, the soql construction is incorrect

Screenshots
If applicable, add screenshots to help explain your problem.
Here is the workbench
[image]<https://user-images.githubusercontent.com/283459/221448785-d0e951f6-2720-4e51-8b33-0c6e951aad0b.png>

Here is the. setup with the same exact soql
[image]<https://user-images.githubusercontent.com/283459/221448853-5af508c5-1fa1-4158-9e90-f899eabe272e.png>
[image]<https://user-images.githubusercontent.com/283459/221448886-ea378bf1-a285-4d3b-b56e-d80ad0b1d537.png>
[{"fieldNameOrPath":"Id","type":"Id","label":"Account Id"},{"fieldNameOrPath":"Sales_Orders__r.Id","type":"Id","label":"Sales Orders Id"},{"fieldNameOrPath":"Sales_Orders__r.Name","type":"String","label":"Sales Order Name Id"}]
Here is the issue in the event log:
[image]<https://user-images.githubusercontent.com/283459/221448990-4a4d756d-6b3d-43f0-b945-434655232105.png>

Desktop (please complete the following information):

  *   Browser Chrome

Additional context
Add any other context about the problem here.

**Comment by martingaleh** [comment]
That's exactly the issue. I must have somehow missed it in the documentation since everyone else seemed to have figured out this fantastic tool.  I'm sure I'll be back.  Thanks again

**Comment by tomansley** [comment]
Hi Martin,

Glad you got it working. I will add that as an enhancement as a few others
have hit this roadblock as well so it must be frustrating people!

Let me know if you hit any other issues.

Cheers
Tom
