### ISSUE TITLE
Service Appointment object is not adding in List View Object and getting exception

### ISSUE THREAD

**Issue by kasanichakravarthi-eaton** [tomansley/SimpliListViews#144]
We are adding Service Appointment object in 'Included Object Types', but it is not reflecting in 'List View Object'. When we verify the logs we could see the below exception in log record

+++
Exception during ListViewProcessBatch.execute() - Upsert failed. First exception on row 7; first error: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, Filter Scope: bad value for restricted picklist field: AssignedToMe: [simpli_lv__Filter_Scope__c] - line: 211 - (simpli_lv)
+++

What version of SLV is currently being used? Latest Version

**To Reproduce**
Seems this issue is with respect to our org. Please help us to debug and resolve the issue.

**Expected behavior**
Service Appointment object should be listed for selection in list views.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] - Chrome

**Comment by tomansley** [comment]
Hello,

Thanks for reaching out. I am in vacation until the 24th April. I will look I to the issue on my return.

Cheers
Tom
________________________________
From: kasanichakravarthi-eaton ***@***.***>
Sent: Tuesday, April 11, 2023 4:56:44 PM
To: tomansley/SimpliListViews ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tomansley/SimpliListViews] Service Appointment object is not adding in List View Object and getting exception (Issue #144)


We are adding Service Appointment object in 'Included Object Types', but it is not reflecting in 'List View Object'. When we verify the logs we could see the below exception in log record

+++
Exception during ListViewProcessBatch.execute() - Upsert failed. First exception on row 7; first error: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, Filter Scope: bad value for restricted picklist field: AssignedToMe: [simpli_lv__Filter_Scope__c] - line: 211 - (simpli_lv)
+++

What version of SLV is currently being used? Latest Version

To Reproduce
Seems this issue is with respect to our org. Please help us to debug and resolve the issue.

Expected behavior
Service Appointment object should be listed for selection in list views.

Desktop (please complete the following information):

  *   Browser [e.g. chrome, safari] - Chrome

**Comment by tomansley** [comment]
Hello,

I have gone ahead and made a small update to the code which should remove
the issue you are seeing. Please install this new package - https://
<SFDC_ORG>/packaging/installPackage.apexp?p0=04t3h000004VaWW

Make sure to change <SFDC_ORG> with your org URL.

Let me know how it goes.

Thanks
Tom

**Comment by kasanichakravarthi-eaton** [comment]
Hi Tom,

I Have upgraded the package and tried to include 'Service Appointment' object in 'Included Object Types', but it is not reflecting in 'List View Object'. Still getting the same old error message only.

Thanks,
Chakravarthi
<img width="674" alt="Error" src="https://user-images.githubusercontent.com/118258428/232687368-b97a20e4-f315-4655-ab79-6997dfbd57bb.png">

**Comment by tomansley** [comment]
Hi Chakravarthi,

Can you please confirm for me that the Filter_Scope__c field has the new AssignedToMe option. Also, I am wondering if I didn't assign that option to the appropriate record types, which would be all of them!

I am not sure if you are able to do that or not. If not I will have to resend an updated package.

Let me know if that makes sense and if you are able to update the option assignments to record type.

Cheers
Tom
________________________________

**Comment by kasanichakravarthi-eaton** [comment]
Hi Tom,

Thanks for your replies. In field: Filter_Scope__c there is no picklist value of 'AssignedToMe' option. I am able to add this value as new picklist value. Also added in record types. Now Service Appointment object is available in 'List View Object' list. This issue is resolved. Thanks a lot for your timely support.

Thanks,
Chakravarthi

**Comment by tomansley** [comment]
Released in v 2.163
