### ISSUE TITLE
Display All Related Records

### ISSUE THREAD

**Issue by thayward2** [tomansley/SimpliListViews#151]
**Describe the bug**
The All Related List Checkbox isn't changing from the scrolling view to the all related record view.

**Simpli List View Version**
What version of SLV is currently being used?
2.167 - Winter 24

**To Reproduce**
1. Go to 'Edit Page on a record'
2. Click on 'The Simple List View Web Component on the record page'
3. Scroll down to 'this shows the configuration settings in the panel on the right, where the component mode is set to 'Related List View''
N/A
**Expected behavior**
Expect the related list view to show all related records without the need to scroll through the list in the fixed component size.

**Screenshots**
I've added a screenshot of the setting.

**Desktop (please complete the following information):**
 - Browser: I'm using Safari.

**Additional context**
I am currently using it in Sandbox.
![Screenshot 2023-11-30 at 16 46 23](https://github.com/tomansley/SimpliListViews/assets/152522171/ac53bbdd-cc80-4020-8297-6b59bc11576b)

**Comment by thayward2** [comment]
Perhaps changes are being made, but I see the new options have disappeared, not visible in Chrome or Safari:
![Screenshot 2023-11-30 at 17 12 40](https://github.com/tomansley/SimpliListViews/assets/152522171/308a1769-7549-4ca5-b32c-2967b01059c6)

**Comment by tomansley** [comment]
Morning - 

I believe I found an issue with the show all related records. I resolved the issue and have created a new package. Take a look and let me know if this resolves your issue. One thing to note is I did not see any issue with browsers. All browsers were able to see the config setting. It was the logic around the displaying of all records that I found a bug for.

Anyway, here is the link (note the link might take 10 minutes to work) - [https://login.salesforce.com/packaging/installPackage.apexp?p0=04t3h000004juH3](javascript:srcUp('https%3A%2F%2Flogin.salesforce.com%2Fpackaging%2FinstallPackage.apexp%3Fp0%3D04t3h000004juH3%26isdtp%3Dp1');)

Please let me know if this resolves the issue so that I can release to the wider set of users.

Cheers
Tom

**Comment by tomansley** [comment]
This has been resolved in the 2.170 release. Please let me know if issues still persist.
