### ISSUE TITLE
How long should initial refresh of List Views take?

### ISSUE THREAD

**Issue by mdufek011888** [tomansley/SimpliListViews#157]
**Describe the bug**
Our company came across your app on the App Exchange & is attempting to set it up on our SF org. We successfully installed the app. But now we are following the Quick Start directions but are hung up on the initial refresh of the List Views. We've clicked the refresh button but the progress bar has been stuck at 0% for 15 minutes.

**Simpli List View Version**
What version of SLV is currently being used?
Simpli-List-Views Summer 2024

**To Reproduce**
1. Go to Simpli List Views Admin app
2. Click on Refresh
3. See progress bar stuck at 0%.

**Expected behavior**
We expect the progress bar to count upwards towards 100%.

**Screenshots**
![image](https://github.com/user-attachments/assets/6e6f908d-16f8-4168-af9c-62d308204b0b)

![Not Progressing](https://github.com/user-attachments/assets/7218d505-a283-43ff-af73-cfb86f19f19b)

**Desktop (please complete the following information):**
 - Chrome

**Comment by tomansley** [comment]
Hello,

Thanks for reaching out. A few things we can look at -

1. Can you verify what version you are using? It should something like 2.293. This can be found by going to the Installed Apps page in Setup.

2. If you go to the Setup -> Environment -> Apex Jobs are the jobs starting? You should see SimpliListViewsProcessing as well as pre and post batches processing. If they are erroring out you should see them in the list. Send me a screenshot of you see something.

3. How big is your org? Do you have thousands or even tens of thousands of lost views? This can be determined by running a query like SELECT count(id) FROM ListView in the console.

4. What kind of org is it? I am guessing an Enterprise or Platform but just checking.

5. It is sometimes the case that the page is not refreshing but the jobs do complete. You should know this by looking at the apex jobs page. Also, the example list view pages should display correctly. I am guessing they are not displaying but just checking.

If you can help with these details that would be a good start.

Cheers
Tom
________________________________
From: mdufek011888 ***@***.***>
Sent: Tuesday, August 27, 2024 4:12:44 PM
To: tomansley/SimpliListViews ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tomansley/SimpliListViews] How long should initial refresh of List Views take? (Issue #157)


Describe the bug
Our company came across your app on the App Exchange & is attempting to set it up on our SF org. We successfully installed the app. But now we are following the Quick Start directions but are hung up on the initial refresh of the List Views. We've clicked the refresh button but the progress bar has been stuck at 0% for 15 minutes.

Simpli List View Version
What version of SLV is currently being used?
Simpli-List-Views Summer 2024

To Reproduce
Steps to reproduce the behavior:

  1.  Go to Simpli List Views Admin app
  2.  Click on Refresh
  3.  See progress bar stuck at 0%.

Expected behavior
We expect the progress bar to count upwards towards 100%.

Screenshots
image.png (view on web)<https://github.com/user-attachments/assets/6e6f908d-16f8-4168-af9c-62d308204b0b>

Not.Progressing.JPG (view on web)<https://github.com/user-attachments/assets/7218d505-a283-43ff-af73-cfb86f19f19b>

Desktop (please complete the following information):

  *   Chrome

**Comment by tomansley** [comment]
Hello,

There has been no response to the data request so closing the bug. Please reopen and provide some requested details above if the issue still persists.

Thanks
Tom
