### ISSUE TITLE
Multi Component not functioning for OpportunityLineItem to OpportunityLineItemSchedule objects

### ISSUE THREAD

**Issue by csilvestre82** [tomansley/SimpliListViews#22]
I've created two list views for OpportunityLineItem and OpportunityLineItemSchedule and joined them on a new lightning page. Unfortunately, when selecting the Product list view row on the left, the schedules on the right do not update to the filtered down list. Also the ID fields are not populating in the columns.

1. Create list views with desired columns/fields including the ID fields
2. In the lightning builder add both the OpportunityLineItem list view and join on the Revenue Schedule list view using the Joined Field Name field as API `OpportunityLineItemId` OR label 
`Line Item ID` and click Save
3. BUG: ID values on columns are NULL
4. BUG: Selecting the product on the left list, does not dynamically filter the schedule records on the right.

Custom List View (Opportunity Line Item Schedules)
![Untitled 5](https://user-images.githubusercontent.com/90287407/132618048-50e88357-b54a-48f5-ba05-18ee3458cc6c.png)

Lightning App Builder Settings
![Untitled 8](https://user-images.githubusercontent.com/90287407/132618293-5b43c1ec-ed3d-4c0d-9464-0d7042165dca.png)

**Comment by tomansley** [comment]
This looks like a great use-case for simpli list views. Awesome. 


I have never actually tried to use the multi list view capability with custom list views but I dont see why they shouldn't work. 


Please post both SOQL statements. I will try to recreate and see what the issue is. 


On Sep 9, 2021 05:37, csilvestre82 ***@***.***> wrote: 

I've created two list views for OpportunityLineItem and OpportunityLineItemSchedule and joined them on a new lightning page. Unfortunately, when selecting the Product list view row on the left, the schedules on the right do not update to the filtered down list. Also the ID fields are not populating in the columns.

Steps to reproduce the behavior:

Create list views with desired columns/fields including the ID fields

In the lightning builder add both the OpportunityLineItem list view and join on the Revenue Schedule list view using the Joined Field Name field as API OpportunityLineItemId OR label
Line Item ID and click Save

BUG: ID values on columns are NULL

BUG: Selecting the product on the left list, does not dynamically filter the schedule records on the right.

Custom List View (Opportunity Line Item Schedules)
 

Lightning App Builder Settings
 

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by csilvestre82** [comment]
Thanks Tom. Ideally what I'm trying to achieve is the ability to update the revenue schedule records (revenue and dates) created under each opportunity line item. Here are my SOQL queries:




```
Opportunity Product (OpportunityLineItem)
-----
SELECT ID,
        Product_Name__c,
        Cost_Center_F__c,
        UnitPrice,
        ServiceDate,
        End_Date__c,
        Forecast_Category__c,
        Override_Revenue_Schedule__c,
        OLI_ID__c        
FROM OpportunityLineItem

```

```
Line Item Schedule (OpportunityLineItemSchedule)
-----
SELECT ID,
        ScheduleDate,
        Revenue,
        Description,
        OpportunityLineItemId,
        OLI_ID__c
FROM OpportunityLineItemSchedule
```

**Comment by tomansley** [comment]
Hello @csilvestre82 ,

I have recreated what I think is the scenario you are trying to create and it seems to work for me without any problems. Here is a screenshot of the data after selecting a single opportunity line item. The schedules are displayed.

![Screen Shot 2021-09-11 at 6 27 03 AM](https://user-images.githubusercontent.com/375321/132936191-e5dd5c8d-0613-4b36-a323-38758864dfe9.png)

Here is the list view configuration I used - 

![Screen Shot 2021-09-11 at 6 27 12 AM](https://user-images.githubusercontent.com/375321/132936202-640b5c1a-e984-4dd2-8a53-a44395007ed3.png)

![Screen Shot 2021-09-11 at 6 28 14 AM](https://user-images.githubusercontent.com/375321/132936208-949e2540-2ba7-45b0-a7d8-cc3e2426fadf.png)

and here is the page configuration I used - 

![Screen Shot 2021-09-11 at 6 32 46 AM](https://user-images.githubusercontent.com/375321/132936287-59965848-1b0e-4327-a455-4800be53ce15.png)

A few things to note - 

1. The component names for the two simpli list view components on the page MUST have different names.
2. You may want to check and ensure all fields have the same case. I am not exactly sure if this could be an issue but its worth checking.
3. Make sure both list view components have "Use Message Channel" checked.
4. When the page is first displayed ALL schedules are displayed as no opportunity line items have been selected. Only after an OLI has been selected will the filtering take place.

Let me know if you are able to get this working.

**Comment by tomansley** [comment]
One thing I noticed is that you want to update the schedules after they have been returned. The solution I am showing above does not allow inline editing as its a custom list view. You of course can have the user select a schedule record and then update the record after it is displayed.

But, I think having a core list view used for the schedules should work just fine as well using the same configuration. If I have some time I will try to update my config to have this happen. This of course is assuming I can create a standard list view for schedules!

**Comment by tomansley** [comment]
@csilvestre82 - after looking at the code further I do not see a reason why it should not be possible to edit custom list view records. I have tested out this capability and it works fine. I will include being able to inline edit of custom list views in the next release.

**Comment by csilvestre82** [comment]
@tomansley - Thanks for the tips and suggestions you've provided. I managed to get the selection process going correctly. Looking forward to your update actions and inline editing of the custom list views!

**Comment by tomansley** [comment]
Resolved.
