### ISSUE TITLE
Page simpliUIListViewsFlow does not exist

### ISSUE THREAD

**Issue by argenturatbek** [tomansley/SimpliListViews#26]
**Describe the bug**
Page simpliUIListViewsFlow does not exist. 

**To Reproduce**

**Expected behavior**
This error is showing up when I try to launch the screen flow with the action. I've followed everything you've showed on the Youtube instructions. Even the flow was similar. Do you know what can be the problem?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version 94.0.4606.61 

**Additional context**

**Comment by tomansley** [comment]
Hello,

This sounds like an issue with the release and not your issue at all. Let me look at it now and try to reproduce and resolve.

Thanks for submitting.

Cheers
Tom

**Comment by argenturatbek** [comment]
Hi Tom, 

Thank you so much!

Argen

**Comment by tomansley** [comment]
Argen,

This should now be resolved. I have released a new version. Please download that from the appexchange listing - https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3A00000FZ7BDUA1

Let me know if this resolves your issue. 

Thanks
Tom

**Comment by argenturatbek** [comment]
Tom, 

Thank you so much! I really appreciate it.

Argen.

**Comment by argenturatbek** [comment]
Hi Tom, 

It is working now perfectly. Thanks! 

I have one more question. So basically, I've put the List View component on the record detail page. Once I select the records, it is recordIds successfully. What I am trying to do is to pass the current page's recordId as well. Do you think that is possible?

Thanks.

**Comment by tomansley** [comment]
If the page that the Simpli list view is on is a standard detail page then I don't think it's possible or I don't know how. 


This is something that I would really like to figure out since being able to set the list view data based on the record detail page would make simpli list views a lot more useful!! 


I will keep looking to see if I can figure out how to do it but at this point I don't know if it's possible. 


On Oct 2, 2021 18:24, Argen Turatbek ***@***.***> wrote: 

Hi Tom,

It is working now perfectly. Thanks!

I have one more question. So basically, I've put the List View component on the record detail page. Once I select the records, it is recordIds successfully. What I am trying to do is to pass the current page's recordId as well. Do you think that is possible?

Thanks.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
