### ISSUE TITLE
Sandbox List Views

### ISSUE THREAD

**Issue by letishaulmer** [tomansley/SimpliListViews#85]
**Describe the bug**
Action Plan List views are working in production but not Sandboxes.  We have created two new sandboxes based on production and they will not load.

**Simpli List View Version**

2.100

**To Reproduce**
1. Go to Account
2. Go to Action Plan Tab > load bar just keeps spinning 

**Expected behavior**
Action Plan Tab would load, you would be able to select an action plan and the tasks would show to edit.

**Screenshots**
![image](https://user-images.githubusercontent.com/98172592/150551873-7c41b982-fdda-4d61-bcdd-954c0c47f292.png)

**Desktop (please complete the following information):**
 - Chrome

**Additional context**

**Comment by tomansley** [comment]
Hello,

Please upgrade to the latest release - v2.114. This includes an
export/import function to allow configuration to be moved between
environments.

After sandboxes are created configuration MUST be moved over or recreated,
otherwise SLV will not work.

Let me know once you have upgraded and exported/imported config whether the
issue still persists.

Thanks
Tom

**Comment by letishaulmer** [comment]
This has resolved the issue.  Thank you!

Thanks,
Letisha

**Comment by tomansley** [comment]
Thanks for letting me know! Glad it worked.
